services:
  - type: web
    name: roblox-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: 10000
